/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmd_902e1de4Holder
{

    public Test.ackcmd_902e1de4 value = null;

    public ackcmd_902e1de4Holder () { }

    public ackcmd_902e1de4Holder (Test.ackcmd_902e1de4 initialValue)
    {
        value = initialValue;
    }

}
