/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmd_902e1de4MetaHolder
{

    public static java.lang.String metaDescriptor[] = { "<MetaData version=\"1.0.0\"><Module name=\"Test\"><Struct name=\"ackcmd_902e1de4\"><Member name=\"private_revCode\"><String length=\"8\"/></Member><Member name=\"private_sndStamp\"><Double/></Member><Member name=\"private_rcvStamp\"><Double/></Member><Member name=\"private_seqNum\"><Long/></Member><Member name=\"private_identity\"><String length=\"128\"/></Member><Member name=\"private_origin\"><Long/></Member><Member name=\"private_host\"><Long/></Member><Member name=\"TestID\"><Long/></Member><Member name=\"ack\"><Long/></Member><Member name=\"error\"><Long/></Member><Member name=\"result\"><String length=\"256\"/></Member><Member name=\"identity\"><String/></Member><Member name=\"host\"><Long/></Member><Member name=\"origin\"><Long/></Member><Member name=\"cmdtype\"><Long/></Member><Member name=\"timeout\"><Double/></Member></Struct></Module></MetaData>" };

    public ackcmd_902e1de4MetaHolder()
    {
    }

}
