/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmdHolder
{

    public Test.ackcmd value = null;

    public ackcmdHolder () { }

    public ackcmdHolder (Test.ackcmd initialValue)
    {
        value = initialValue;
    }

}
