/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public class ackcmd_902e1de4TypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public ackcmd_902e1de4TypeSupport()
    {
        super("Test::ackcmd_902e1de4",
              "",
              "TestID",
              null,
              Test.ackcmd_902e1de4MetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new ackcmd_902e1de4DataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new ackcmd_902e1de4DataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new ackcmd_902e1de4DataReaderViewImpl(this);
    }
}
