/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmdTypeSupportHolder
{

    public Test.ackcmdTypeSupport value = null;

    public ackcmdTypeSupportHolder()
    {
    }

    public ackcmdTypeSupportHolder(Test.ackcmdTypeSupport initialValue)
    {
        value = initialValue;
    }

}
