/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmdDataReaderHolder
{

    public Test.ackcmdDataReader value = null;

    public ackcmdDataReaderHolder()
    {
    }

    public ackcmdDataReaderHolder(Test.ackcmdDataReader initialValue)
    {
        value = initialValue;
    }

}
