/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmd_902e1de4 {

    public java.lang.String private_revCode = "";
    public double private_sndStamp;
    public double private_rcvStamp;
    public int private_seqNum;
    public java.lang.String private_identity = "";
    public int private_origin;
    public int private_host;
    public int TestID;
    public int ack;
    public int error;
    public java.lang.String result = "";
    public java.lang.String identity = "";
    public int host;
    public int origin;
    public int cmdtype;
    public double timeout;

    public ackcmd_902e1de4() {
    }

    public ackcmd_902e1de4(
        java.lang.String _private_revCode,
        double _private_sndStamp,
        double _private_rcvStamp,
        int _private_seqNum,
        java.lang.String _private_identity,
        int _private_origin,
        int _private_host,
        int _TestID,
        int _ack,
        int _error,
        java.lang.String _result,
        java.lang.String _identity,
        int _host,
        int _origin,
        int _cmdtype,
        double _timeout)
    {
        private_revCode = _private_revCode;
        private_sndStamp = _private_sndStamp;
        private_rcvStamp = _private_rcvStamp;
        private_seqNum = _private_seqNum;
        private_identity = _private_identity;
        private_origin = _private_origin;
        private_host = _private_host;
        TestID = _TestID;
        ack = _ack;
        error = _error;
        result = _result;
        identity = _identity;
        host = _host;
        origin = _origin;
        cmdtype = _cmdtype;
        timeout = _timeout;
    }

}
