/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmd_902e1de4TypeSupportHolder
{

    public Test.ackcmd_902e1de4TypeSupport value = null;

    public ackcmd_902e1de4TypeSupportHolder()
    {
    }

    public ackcmd_902e1de4TypeSupportHolder(Test.ackcmd_902e1de4TypeSupport initialValue)
    {
        value = initialValue;
    }

}
