/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface ackcmd_902e1de4DataReader extends
    Test.ackcmd_902e1de4DataReaderOperations,
    DDS.DataReader
{
}
