/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class ackcmdSeqHolder
{

    public Test.ackcmd value[] = null;

    public ackcmdSeqHolder()
    {
    }

    public ackcmdSeqHolder(Test.ackcmd[] initialValue)
    {
        value = initialValue;
    }

}
