/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class arraysHolder
{

    public Test.arrays value = null;

    public arraysHolder () { }

    public arraysHolder (Test.arrays initialValue)
    {
        value = initialValue;
    }

}
