/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface arrays_f7d0e190DataReaderView extends
    Test.arrays_f7d0e190DataReaderViewOperations,
    DDS.DataReaderView
{
}
