/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface arraysDataReaderView extends
    Test.arraysDataReaderViewOperations,
    DDS.DataReaderView
{
}
