/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class arraysDataReaderHolder
{

    public Test.arraysDataReader value = null;

    public arraysDataReaderHolder()
    {
    }

    public arraysDataReaderHolder(Test.arraysDataReader initialValue)
    {
        value = initialValue;
    }

}
