/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class arraysTypeSupportHolder
{

    public Test.arraysTypeSupport value = null;

    public arraysTypeSupportHolder()
    {
    }

    public arraysTypeSupportHolder(Test.arraysTypeSupport initialValue)
    {
        value = initialValue;
    }

}
