/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class arrays_f7d0e190Holder
{

    public Test.arrays_f7d0e190 value = null;

    public arrays_f7d0e190Holder () { }

    public arrays_f7d0e190Holder (Test.arrays_f7d0e190 initialValue)
    {
        value = initialValue;
    }

}
