/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class arrays_f7d0e190DataReaderViewHolder
{

    public Test.arrays_f7d0e190DataReaderView value = null;

    public arrays_f7d0e190DataReaderViewHolder()
    {
    }

    public arrays_f7d0e190DataReaderViewHolder(Test.arrays_f7d0e190DataReaderView initialValue)
    {
        value = initialValue;
    }

}
