/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class arraysDataWriterHolder
{

    public Test.arraysDataWriter value = null;

    public arraysDataWriterHolder()
    {
    }

    public arraysDataWriterHolder(Test.arraysDataWriter initialValue)
    {
        value = initialValue;
    }

}
