/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enterControl_abb0d976DataReaderHolder
{

    public Test.command_enterControl_abb0d976DataReader value = null;

    public command_enterControl_abb0d976DataReaderHolder()
    {
    }

    public command_enterControl_abb0d976DataReaderHolder(Test.command_enterControl_abb0d976DataReader initialValue)
    {
        value = initialValue;
    }

}
