/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_start_74351d61DataReaderHolder
{

    public Test.command_start_74351d61DataReader value = null;

    public command_start_74351d61DataReaderHolder()
    {
    }

    public command_start_74351d61DataReaderHolder(Test.command_start_74351d61DataReader initialValue)
    {
        value = initialValue;
    }

}
