/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enableHolder
{

    public Test.command_enable value = null;

    public command_enableHolder () { }

    public command_enableHolder (Test.command_enable initialValue)
    {
        value = initialValue;
    }

}
