/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abort_1c6758a1DataReaderViewHolder
{

    public Test.command_abort_1c6758a1DataReaderView value = null;

    public command_abort_1c6758a1DataReaderViewHolder()
    {
    }

    public command_abort_1c6758a1DataReaderViewHolder(Test.command_abort_1c6758a1DataReaderView initialValue)
    {
        value = initialValue;
    }

}
