/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abort_1c6758a1Holder
{

    public Test.command_abort_1c6758a1 value = null;

    public command_abort_1c6758a1Holder () { }

    public command_abort_1c6758a1Holder (Test.command_abort_1c6758a1 initialValue)
    {
        value = initialValue;
    }

}
