/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abortDataReaderHolder
{

    public Test.command_abortDataReader value = null;

    public command_abortDataReaderHolder()
    {
    }

    public command_abortDataReaderHolder(Test.command_abortDataReader initialValue)
    {
        value = initialValue;
    }

}
