/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setValueDataReaderViewHolder
{

    public Test.command_setValueDataReaderView value = null;

    public command_setValueDataReaderViewHolder()
    {
    }

    public command_setValueDataReaderViewHolder(Test.command_setValueDataReaderView initialValue)
    {
        value = initialValue;
    }

}
