/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setAuthListDataWriterHolder
{

    public Test.command_setAuthListDataWriter value = null;

    public command_setAuthListDataWriterHolder()
    {
    }

    public command_setAuthListDataWriterHolder(Test.command_setAuthListDataWriter initialValue)
    {
        value = initialValue;
    }

}
