/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevelHolder
{

    public Test.command_setLogLevel value = null;

    public command_setLogLevelHolder () { }

    public command_setLogLevelHolder (Test.command_setLogLevel initialValue)
    {
        value = initialValue;
    }

}
