/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enableDataWriterHolder
{

    public Test.command_enableDataWriter value = null;

    public command_enableDataWriterHolder()
    {
    }

    public command_enableDataWriterHolder(Test.command_enableDataWriter initialValue)
    {
        value = initialValue;
    }

}
