/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setValue_caab4364SeqHolder
{

    public Test.command_setValue_caab4364 value[] = null;

    public command_setValue_caab4364SeqHolder()
    {
    }

    public command_setValue_caab4364SeqHolder(Test.command_setValue_caab4364[] initialValue)
    {
        value = initialValue;
    }

}
