/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface command_setScalars_0fcc702bDataReader extends
    Test.command_setScalars_0fcc702bDataReaderOperations,
    DDS.DataReader
{
}
