/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControlMetaHolder
{

    public static java.lang.String metaDescriptor[] = { "<MetaData version=\"1.0.0\"><Module name=\"Test\"><Struct name=\"command_exitControl\"><Member name=\"TestID\"><Long/></Member><Member name=\"private_revCode\"><String length=\"8\"/></Member><Member name=\"private_sndStamp\"><Double/></Member><Member name=\"private_rcvStamp\"><Double/></Member><Member name=\"private_seqNum\"><Long/></Member><Member name=\"private_identity\"><String length=\"128\"/></Member><Member name=\"private_origin\"><Long/></Member><Member name=\"private_host\"><Long/></Member></Struct></Module></MetaData>" };

    public command_exitControlMetaHolder()
    {
    }

}
