/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalarsDataReaderHolder
{

    public Test.command_setScalarsDataReader value = null;

    public command_setScalarsDataReaderHolder()
    {
    }

    public command_setScalarsDataReaderHolder(Test.command_setScalarsDataReader initialValue)
    {
        value = initialValue;
    }

}
