/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface command_exitControlDataReader extends
    Test.command_exitControlDataReaderOperations,
    DDS.DataReader
{
}
