/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public class command_setScalars_0fcc702bTypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public command_setScalars_0fcc702bTypeSupport()
    {
        super("Test::command_setScalars_0fcc702b",
              "",
              "TestID",
              null,
              Test.command_setScalars_0fcc702bMetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new command_setScalars_0fcc702bDataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new command_setScalars_0fcc702bDataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new command_setScalars_0fcc702bDataReaderViewImpl(this);
    }
}
