/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_disableSeqHolder
{

    public Test.command_disable value[] = null;

    public command_disableSeqHolder()
    {
    }

    public command_disableSeqHolder(Test.command_disable[] initialValue)
    {
        value = initialValue;
    }

}
