/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_start_74351d61Holder
{

    public Test.command_start_74351d61 value = null;

    public command_start_74351d61Holder () { }

    public command_start_74351d61Holder (Test.command_start_74351d61 initialValue)
    {
        value = initialValue;
    }

}
