/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControlDataReaderHolder
{

    public Test.command_exitControlDataReader value = null;

    public command_exitControlDataReaderHolder()
    {
    }

    public command_exitControlDataReaderHolder(Test.command_exitControlDataReader initialValue)
    {
        value = initialValue;
    }

}
