/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_standbyDataReaderHolder
{

    public Test.command_standbyDataReader value = null;

    public command_standbyDataReaderHolder()
    {
    }

    public command_standbyDataReaderHolder(Test.command_standbyDataReader initialValue)
    {
        value = initialValue;
    }

}
