/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_faultDataReaderHolder
{

    public Test.command_faultDataReader value = null;

    public command_faultDataReaderHolder()
    {
    }

    public command_faultDataReaderHolder(Test.command_faultDataReader initialValue)
    {
        value = initialValue;
    }

}
