/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setValueTypeSupportHolder
{

    public Test.command_setValueTypeSupport value = null;

    public command_setValueTypeSupportHolder()
    {
    }

    public command_setValueTypeSupportHolder(Test.command_setValueTypeSupport initialValue)
    {
        value = initialValue;
    }

}
