/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setValueDataReaderHolder
{

    public Test.command_setValueDataReader value = null;

    public command_setValueDataReaderHolder()
    {
    }

    public command_setValueDataReaderHolder(Test.command_setValueDataReader initialValue)
    {
        value = initialValue;
    }

}
