/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalarsSeqHolder
{

    public Test.command_setScalars value[] = null;

    public command_setScalarsSeqHolder()
    {
    }

    public command_setScalarsSeqHolder(Test.command_setScalars[] initialValue)
    {
        value = initialValue;
    }

}
