/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_waitDataReaderViewHolder
{

    public Test.command_waitDataReaderView value = null;

    public command_waitDataReaderViewHolder()
    {
    }

    public command_waitDataReaderViewHolder(Test.command_waitDataReaderView initialValue)
    {
        value = initialValue;
    }

}
