/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevel_48c8505dDataReaderViewHolder
{

    public Test.command_setLogLevel_48c8505dDataReaderView value = null;

    public command_setLogLevel_48c8505dDataReaderViewHolder()
    {
    }

    public command_setLogLevel_48c8505dDataReaderViewHolder(Test.command_setLogLevel_48c8505dDataReaderView initialValue)
    {
        value = initialValue;
    }

}
