/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setArraysDataReaderViewHolder
{

    public Test.command_setArraysDataReaderView value = null;

    public command_setArraysDataReaderViewHolder()
    {
    }

    public command_setArraysDataReaderViewHolder(Test.command_setArraysDataReaderView initialValue)
    {
        value = initialValue;
    }

}
