/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_disableDataReaderViewHolder
{

    public Test.command_disableDataReaderView value = null;

    public command_disableDataReaderViewHolder()
    {
    }

    public command_disableDataReaderViewHolder(Test.command_disableDataReaderView initialValue)
    {
        value = initialValue;
    }

}
