/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enterControlDataReaderHolder
{

    public Test.command_enterControlDataReader value = null;

    public command_enterControlDataReaderHolder()
    {
    }

    public command_enterControlDataReaderHolder(Test.command_enterControlDataReader initialValue)
    {
        value = initialValue;
    }

}
