/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_disableDataWriterHolder
{

    public Test.command_disableDataWriter value = null;

    public command_disableDataWriterHolder()
    {
    }

    public command_disableDataWriterHolder(Test.command_disableDataWriter initialValue)
    {
        value = initialValue;
    }

}
