/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalarsTypeSupportHolder
{

    public Test.command_setScalarsTypeSupport value = null;

    public command_setScalarsTypeSupportHolder()
    {
    }

    public command_setScalarsTypeSupportHolder(Test.command_setScalarsTypeSupport initialValue)
    {
        value = initialValue;
    }

}
