/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_disable_79c48b19DataReaderViewHolder
{

    public Test.command_disable_79c48b19DataReaderView value = null;

    public command_disable_79c48b19DataReaderViewHolder()
    {
    }

    public command_disable_79c48b19DataReaderViewHolder(Test.command_disable_79c48b19DataReaderView initialValue)
    {
        value = initialValue;
    }

}
