/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enterControlDataWriterHolder
{

    public Test.command_enterControlDataWriter value = null;

    public command_enterControlDataWriterHolder()
    {
    }

    public command_enterControlDataWriterHolder(Test.command_enterControlDataWriter initialValue)
    {
        value = initialValue;
    }

}
