/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_startDataReaderHolder
{

    public Test.command_startDataReader value = null;

    public command_startDataReaderHolder()
    {
    }

    public command_startDataReaderHolder(Test.command_startDataReader initialValue)
    {
        value = initialValue;
    }

}
