/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_standby_7054c900Holder
{

    public Test.command_standby_7054c900 value = null;

    public command_standby_7054c900Holder () { }

    public command_standby_7054c900Holder (Test.command_standby_7054c900 initialValue)
    {
        value = initialValue;
    }

}
