/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abortTypeSupportHolder
{

    public Test.command_abortTypeSupport value = null;

    public command_abortTypeSupportHolder()
    {
    }

    public command_abortTypeSupportHolder(Test.command_abortTypeSupport initialValue)
    {
        value = initialValue;
    }

}
