/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setArraysSeqHolder
{

    public Test.command_setArrays value[] = null;

    public command_setArraysSeqHolder()
    {
    }

    public command_setArraysSeqHolder(Test.command_setArrays[] initialValue)
    {
        value = initialValue;
    }

}
