/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControl_9b992131Holder
{

    public Test.command_exitControl_9b992131 value = null;

    public command_exitControl_9b992131Holder () { }

    public command_exitControl_9b992131Holder (Test.command_exitControl_9b992131 initialValue)
    {
        value = initialValue;
    }

}
