/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevel_48c8505dDataReaderHolder
{

    public Test.command_setLogLevel_48c8505dDataReader value = null;

    public command_setLogLevel_48c8505dDataReaderHolder()
    {
    }

    public command_setLogLevel_48c8505dDataReaderHolder(Test.command_setLogLevel_48c8505dDataReader initialValue)
    {
        value = initialValue;
    }

}
