/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface command_disable_79c48b19DataWriter extends
    Test.command_disable_79c48b19DataWriterOperations,
    DDS.DataWriter
{
}
