/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_disableHolder
{

    public Test.command_disable value = null;

    public command_disableHolder () { }

    public command_disableHolder (Test.command_disable initialValue)
    {
        value = initialValue;
    }

}
