/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enableDataReaderHolder
{

    public Test.command_enableDataReader value = null;

    public command_enableDataReaderHolder()
    {
    }

    public command_enableDataReaderHolder(Test.command_enableDataReader initialValue)
    {
        value = initialValue;
    }

}
