/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enable_69193c6fDataReaderViewHolder
{

    public Test.command_enable_69193c6fDataReaderView value = null;

    public command_enable_69193c6fDataReaderViewHolder()
    {
    }

    public command_enable_69193c6fDataReaderViewHolder(Test.command_enable_69193c6fDataReaderView initialValue)
    {
        value = initialValue;
    }

}
