/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_startTypeSupportHolder
{

    public Test.command_startTypeSupport value = null;

    public command_startTypeSupportHolder()
    {
    }

    public command_startTypeSupportHolder(Test.command_startTypeSupport initialValue)
    {
        value = initialValue;
    }

}
