/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_startDataWriterHolder
{

    public Test.command_startDataWriter value = null;

    public command_startDataWriterHolder()
    {
    }

    public command_startDataWriterHolder(Test.command_startDataWriter initialValue)
    {
        value = initialValue;
    }

}
