/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abortDataWriterHolder
{

    public Test.command_abortDataWriter value = null;

    public command_abortDataWriterHolder()
    {
    }

    public command_abortDataWriterHolder(Test.command_abortDataWriter initialValue)
    {
        value = initialValue;
    }

}
