/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_fault_4b850e28DataReaderViewHolder
{

    public Test.command_fault_4b850e28DataReaderView value = null;

    public command_fault_4b850e28DataReaderViewHolder()
    {
    }

    public command_fault_4b850e28DataReaderViewHolder(Test.command_fault_4b850e28DataReaderView initialValue)
    {
        value = initialValue;
    }

}
