/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setArraysHolder
{

    public Test.command_setArrays value = null;

    public command_setArraysHolder () { }

    public command_setArraysHolder (Test.command_setArrays initialValue)
    {
        value = initialValue;
    }

}
