/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_faultSeqHolder
{

    public Test.command_fault value[] = null;

    public command_faultSeqHolder()
    {
    }

    public command_faultSeqHolder(Test.command_fault[] initialValue)
    {
        value = initialValue;
    }

}
