/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalars_0fcc702bDataReaderHolder
{

    public Test.command_setScalars_0fcc702bDataReader value = null;

    public command_setScalars_0fcc702bDataReaderHolder()
    {
    }

    public command_setScalars_0fcc702bDataReaderHolder(Test.command_setScalars_0fcc702bDataReader initialValue)
    {
        value = initialValue;
    }

}
