/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControlDataReaderViewHolder
{

    public Test.command_exitControlDataReaderView value = null;

    public command_exitControlDataReaderViewHolder()
    {
    }

    public command_exitControlDataReaderViewHolder(Test.command_exitControlDataReaderView initialValue)
    {
        value = initialValue;
    }

}
