/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevelDataWriterHolder
{

    public Test.command_setLogLevelDataWriter value = null;

    public command_setLogLevelDataWriterHolder()
    {
    }

    public command_setLogLevelDataWriterHolder(Test.command_setLogLevelDataWriter initialValue)
    {
        value = initialValue;
    }

}
