/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setAuthListHolder
{

    public Test.command_setAuthList value = null;

    public command_setAuthListHolder () { }

    public command_setAuthListHolder (Test.command_setAuthList initialValue)
    {
        value = initialValue;
    }

}
