/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_faultHolder
{

    public Test.command_fault value = null;

    public command_faultHolder () { }

    public command_faultHolder (Test.command_fault initialValue)
    {
        value = initialValue;
    }

}
