/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_standby_7054c900TypeSupportHolder
{

    public Test.command_standby_7054c900TypeSupport value = null;

    public command_standby_7054c900TypeSupportHolder()
    {
    }

    public command_standby_7054c900TypeSupportHolder(Test.command_standby_7054c900TypeSupport initialValue)
    {
        value = initialValue;
    }

}
