/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setAuthList_a648281dHolder
{

    public Test.command_setAuthList_a648281d value = null;

    public command_setAuthList_a648281dHolder () { }

    public command_setAuthList_a648281dHolder (Test.command_setAuthList_a648281d initialValue)
    {
        value = initialValue;
    }

}
