/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abortDataReaderViewHolder
{

    public Test.command_abortDataReaderView value = null;

    public command_abortDataReaderViewHolder()
    {
    }

    public command_abortDataReaderViewHolder(Test.command_abortDataReaderView initialValue)
    {
        value = initialValue;
    }

}
