/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enterControlSeqHolder
{

    public Test.command_enterControl value[] = null;

    public command_enterControlSeqHolder()
    {
    }

    public command_enterControlSeqHolder(Test.command_enterControl[] initialValue)
    {
        value = initialValue;
    }

}
