/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalars_0fcc702bHolder
{

    public Test.command_setScalars_0fcc702b value = null;

    public command_setScalars_0fcc702bHolder () { }

    public command_setScalars_0fcc702bHolder (Test.command_setScalars_0fcc702b initialValue)
    {
        value = initialValue;
    }

}
