/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevel_48c8505dTypeSupportHolder
{

    public Test.command_setLogLevel_48c8505dTypeSupport value = null;

    public command_setLogLevel_48c8505dTypeSupportHolder()
    {
    }

    public command_setLogLevel_48c8505dTypeSupportHolder(Test.command_setLogLevel_48c8505dTypeSupport initialValue)
    {
        value = initialValue;
    }

}
