/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControlTypeSupportHolder
{

    public Test.command_exitControlTypeSupport value = null;

    public command_exitControlTypeSupportHolder()
    {
    }

    public command_exitControlTypeSupportHolder(Test.command_exitControlTypeSupport initialValue)
    {
        value = initialValue;
    }

}
