/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_standbySeqHolder
{

    public Test.command_standby value[] = null;

    public command_standbySeqHolder()
    {
    }

    public command_standbySeqHolder(Test.command_standby[] initialValue)
    {
        value = initialValue;
    }

}
