/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalarsHolder
{

    public Test.command_setScalars value = null;

    public command_setScalarsHolder () { }

    public command_setScalarsHolder (Test.command_setScalars initialValue)
    {
        value = initialValue;
    }

}
