/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_fault_4b850e28Holder
{

    public Test.command_fault_4b850e28 value = null;

    public command_fault_4b850e28Holder () { }

    public command_fault_4b850e28Holder (Test.command_fault_4b850e28 initialValue)
    {
        value = initialValue;
    }

}
