/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalarsDataWriterHolder
{

    public Test.command_setScalarsDataWriter value = null;

    public command_setScalarsDataWriterHolder()
    {
    }

    public command_setScalarsDataWriterHolder(Test.command_setScalarsDataWriter initialValue)
    {
        value = initialValue;
    }

}
