/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setAuthListDataReaderViewHolder
{

    public Test.command_setAuthListDataReaderView value = null;

    public command_setAuthListDataReaderViewHolder()
    {
    }

    public command_setAuthListDataReaderViewHolder(Test.command_setAuthListDataReaderView initialValue)
    {
        value = initialValue;
    }

}
