/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setArraysTypeSupportHolder
{

    public Test.command_setArraysTypeSupport value = null;

    public command_setArraysTypeSupportHolder()
    {
    }

    public command_setArraysTypeSupportHolder(Test.command_setArraysTypeSupport initialValue)
    {
        value = initialValue;
    }

}
