/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setAuthList_a648281dSeqHolder
{

    public Test.command_setAuthList_a648281d value[] = null;

    public command_setAuthList_a648281dSeqHolder()
    {
    }

    public command_setAuthList_a648281dSeqHolder(Test.command_setAuthList_a648281d[] initialValue)
    {
        value = initialValue;
    }

}
