/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abort_1c6758a1DataWriterHolder
{

    public Test.command_abort_1c6758a1DataWriter value = null;

    public command_abort_1c6758a1DataWriterHolder()
    {
    }

    public command_abort_1c6758a1DataWriterHolder(Test.command_abort_1c6758a1DataWriter initialValue)
    {
        value = initialValue;
    }

}
