/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_waitHolder
{

    public Test.command_wait value = null;

    public command_waitHolder () { }

    public command_waitHolder (Test.command_wait initialValue)
    {
        value = initialValue;
    }

}
