/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enterControlTypeSupportHolder
{

    public Test.command_enterControlTypeSupport value = null;

    public command_enterControlTypeSupportHolder()
    {
    }

    public command_enterControlTypeSupportHolder(Test.command_enterControlTypeSupport initialValue)
    {
        value = initialValue;
    }

}
