/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setAuthList_a648281dDataReaderHolder
{

    public Test.command_setAuthList_a648281dDataReader value = null;

    public command_setAuthList_a648281dDataReaderHolder()
    {
    }

    public command_setAuthList_a648281dDataReaderHolder(Test.command_setAuthList_a648281dDataReader initialValue)
    {
        value = initialValue;
    }

}
