/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_standbyTypeSupportHolder
{

    public Test.command_standbyTypeSupport value = null;

    public command_standbyTypeSupportHolder()
    {
    }

    public command_standbyTypeSupportHolder(Test.command_standbyTypeSupport initialValue)
    {
        value = initialValue;
    }

}
