/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_disableTypeSupportHolder
{

    public Test.command_disableTypeSupport value = null;

    public command_disableTypeSupportHolder()
    {
    }

    public command_disableTypeSupportHolder(Test.command_disableTypeSupport initialValue)
    {
        value = initialValue;
    }

}
