/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_waitSeqHolder
{

    public Test.command_wait value[] = null;

    public command_waitSeqHolder()
    {
    }

    public command_waitSeqHolder(Test.command_wait[] initialValue)
    {
        value = initialValue;
    }

}
