/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setValueHolder
{

    public Test.command_setValue value = null;

    public command_setValueHolder () { }

    public command_setValueHolder (Test.command_setValue initialValue)
    {
        value = initialValue;
    }

}
