/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface command_fault_4b850e28DataReaderView extends
    Test.command_fault_4b850e28DataReaderViewOperations,
    DDS.DataReaderView
{
}
