/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_waitTypeSupportHolder
{

    public Test.command_waitTypeSupport value = null;

    public command_waitTypeSupportHolder()
    {
    }

    public command_waitTypeSupportHolder(Test.command_waitTypeSupport initialValue)
    {
        value = initialValue;
    }

}
