/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface command_setArrays_e11a567aDataReaderView extends
    Test.command_setArrays_e11a567aDataReaderViewOperations,
    DDS.DataReaderView
{
}
