/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_disable_79c48b19Holder
{

    public Test.command_disable_79c48b19 value = null;

    public command_disable_79c48b19Holder () { }

    public command_disable_79c48b19Holder (Test.command_disable_79c48b19 initialValue)
    {
        value = initialValue;
    }

}
