/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_waitDataReaderHolder
{

    public Test.command_waitDataReader value = null;

    public command_waitDataReaderHolder()
    {
    }

    public command_waitDataReaderHolder(Test.command_waitDataReader initialValue)
    {
        value = initialValue;
    }

}
