/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setArrays_e11a567aHolder
{

    public Test.command_setArrays_e11a567a value = null;

    public command_setArrays_e11a567aHolder () { }

    public command_setArrays_e11a567aHolder (Test.command_setArrays_e11a567a initialValue)
    {
        value = initialValue;
    }

}
