/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControl_9b992131SeqHolder
{

    public Test.command_exitControl_9b992131 value[] = null;

    public command_exitControl_9b992131SeqHolder()
    {
    }

    public command_exitControl_9b992131SeqHolder(Test.command_exitControl_9b992131[] initialValue)
    {
        value = initialValue;
    }

}
