/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setAuthListDataReaderHolder
{

    public Test.command_setAuthListDataReader value = null;

    public command_setAuthListDataReaderHolder()
    {
    }

    public command_setAuthListDataReaderHolder(Test.command_setAuthListDataReader initialValue)
    {
        value = initialValue;
    }

}
