/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_wait_1b2e8a6fDataReaderHolder
{

    public Test.command_wait_1b2e8a6fDataReader value = null;

    public command_wait_1b2e8a6fDataReaderHolder()
    {
    }

    public command_wait_1b2e8a6fDataReaderHolder(Test.command_wait_1b2e8a6fDataReader initialValue)
    {
        value = initialValue;
    }

}
