/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_abort_1c6758a1DataReaderHolder
{

    public Test.command_abort_1c6758a1DataReader value = null;

    public command_abort_1c6758a1DataReaderHolder()
    {
    }

    public command_abort_1c6758a1DataReaderHolder(Test.command_abort_1c6758a1DataReader initialValue)
    {
        value = initialValue;
    }

}
