/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevel_48c8505dHolder
{

    public Test.command_setLogLevel_48c8505d value = null;

    public command_setLogLevel_48c8505dHolder () { }

    public command_setLogLevel_48c8505dHolder (Test.command_setLogLevel_48c8505d initialValue)
    {
        value = initialValue;
    }

}
