/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enterControlHolder
{

    public Test.command_enterControl value = null;

    public command_enterControlHolder () { }

    public command_enterControlHolder (Test.command_enterControl initialValue)
    {
        value = initialValue;
    }

}
