/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControl_9b992131TypeSupportHolder
{

    public Test.command_exitControl_9b992131TypeSupport value = null;

    public command_exitControl_9b992131TypeSupportHolder()
    {
    }

    public command_exitControl_9b992131TypeSupportHolder(Test.command_exitControl_9b992131TypeSupport initialValue)
    {
        value = initialValue;
    }

}
