/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_exitControl_9b992131DataWriterHolder
{

    public Test.command_exitControl_9b992131DataWriter value = null;

    public command_exitControl_9b992131DataWriterHolder()
    {
    }

    public command_exitControl_9b992131DataWriterHolder(Test.command_exitControl_9b992131DataWriter initialValue)
    {
        value = initialValue;
    }

}
