/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_startDataReaderViewHolder
{

    public Test.command_startDataReaderView value = null;

    public command_startDataReaderViewHolder()
    {
    }

    public command_startDataReaderViewHolder(Test.command_startDataReaderView initialValue)
    {
        value = initialValue;
    }

}
