/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_startSeqHolder
{

    public Test.command_start value[] = null;

    public command_startSeqHolder()
    {
    }

    public command_startSeqHolder(Test.command_start[] initialValue)
    {
        value = initialValue;
    }

}
