/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface command_setLogLevelDataWriter extends
    Test.command_setLogLevelDataWriterOperations,
    DDS.DataWriter
{
}
