/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_faultDataWriterHolder
{

    public Test.command_faultDataWriter value = null;

    public command_faultDataWriterHolder()
    {
    }

    public command_faultDataWriterHolder(Test.command_faultDataWriter initialValue)
    {
        value = initialValue;
    }

}
