/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_waitDataWriterHolder
{

    public Test.command_waitDataWriter value = null;

    public command_waitDataWriterHolder()
    {
    }

    public command_waitDataWriterHolder(Test.command_waitDataWriter initialValue)
    {
        value = initialValue;
    }

}
