/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:25+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_faultDataReaderViewHolder
{

    public Test.command_faultDataReaderView value = null;

    public command_faultDataReaderViewHolder()
    {
    }

    public command_faultDataReaderViewHolder(Test.command_faultDataReaderView initialValue)
    {
        value = initialValue;
    }

}
