/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setArraysDataWriterHolder
{

    public Test.command_setArraysDataWriter value = null;

    public command_setArraysDataWriterHolder()
    {
    }

    public command_setArraysDataWriterHolder(Test.command_setArraysDataWriter initialValue)
    {
        value = initialValue;
    }

}
