/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevelDataReaderHolder
{

    public Test.command_setLogLevelDataReader value = null;

    public command_setLogLevelDataReaderHolder()
    {
    }

    public command_setLogLevelDataReaderHolder(Test.command_setLogLevelDataReader initialValue)
    {
        value = initialValue;
    }

}
