/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public class command_setLogLevel_48c8505dTypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public command_setLogLevel_48c8505dTypeSupport()
    {
        super("Test::command_setLogLevel_48c8505d",
              "",
              "TestID",
              null,
              Test.command_setLogLevel_48c8505dMetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new command_setLogLevel_48c8505dDataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new command_setLogLevel_48c8505dDataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new command_setLogLevel_48c8505dDataReaderViewImpl(this);
    }
}
