/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setValue_caab4364TypeSupportHolder
{

    public Test.command_setValue_caab4364TypeSupport value = null;

    public command_setValue_caab4364TypeSupportHolder()
    {
    }

    public command_setValue_caab4364TypeSupportHolder(Test.command_setValue_caab4364TypeSupport initialValue)
    {
        value = initialValue;
    }

}
