/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_enable_69193c6fHolder
{

    public Test.command_enable_69193c6f value = null;

    public command_enable_69193c6fHolder () { }

    public command_enable_69193c6fHolder (Test.command_enable_69193c6f initialValue)
    {
        value = initialValue;
    }

}
