/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setArrays_e11a567aDataReaderHolder
{

    public Test.command_setArrays_e11a567aDataReader value = null;

    public command_setArrays_e11a567aDataReaderHolder()
    {
    }

    public command_setArrays_e11a567aDataReaderHolder(Test.command_setArrays_e11a567aDataReader initialValue)
    {
        value = initialValue;
    }

}
