/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:30+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface command_exitControl_9b992131DataReader extends
    Test.command_exitControl_9b992131DataReaderOperations,
    DDS.DataReader
{
}
