/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setLogLevelDataReaderViewHolder
{

    public Test.command_setLogLevelDataReaderView value = null;

    public command_setLogLevelDataReaderViewHolder()
    {
    }

    public command_setLogLevelDataReaderViewHolder(Test.command_setLogLevelDataReaderView initialValue)
    {
        value = initialValue;
    }

}
