/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class command_setScalarsDataReaderViewHolder
{

    public Test.command_setScalarsDataReaderView value = null;

    public command_setScalarsDataReaderViewHolder()
    {
    }

    public command_setScalarsDataReaderViewHolder(Test.command_setScalarsDataReaderView initialValue)
    {
        value = initialValue;
    }

}
