/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevel_7aeafb06DataReaderHolder
{

    public Test.logevent_logLevel_7aeafb06DataReader value = null;

    public logevent_logLevel_7aeafb06DataReaderHolder()
    {
    }

    public logevent_logLevel_7aeafb06DataReaderHolder(Test.logevent_logLevel_7aeafb06DataReader initialValue)
    {
        value = initialValue;
    }

}
