/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevel_7aeafb06TypeSupportHolder
{

    public Test.logevent_logLevel_7aeafb06TypeSupport value = null;

    public logevent_logLevel_7aeafb06TypeSupportHolder()
    {
    }

    public logevent_logLevel_7aeafb06TypeSupportHolder(Test.logevent_logLevel_7aeafb06TypeSupport initialValue)
    {
        value = initialValue;
    }

}
