/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arraysDataReaderViewHolder
{

    public Test.logevent_arraysDataReaderView value = null;

    public logevent_arraysDataReaderViewHolder()
    {
    }

    public logevent_arraysDataReaderViewHolder(Test.logevent_arraysDataReaderView initialValue)
    {
        value = initialValue;
    }

}
