/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logMessageTypeSupportHolder
{

    public Test.logevent_logMessageTypeSupport value = null;

    public logevent_logMessageTypeSupportHolder()
    {
    }

    public logevent_logMessageTypeSupportHolder(Test.logevent_logMessageTypeSupport initialValue)
    {
        value = initialValue;
    }

}
