/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalarsHolder
{

    public Test.logevent_scalars value = null;

    public logevent_scalarsHolder () { }

    public logevent_scalarsHolder (Test.logevent_scalars initialValue)
    {
        value = initialValue;
    }

}
