/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_errorCodeDataWriterHolder
{

    public Test.logevent_errorCodeDataWriter value = null;

    public logevent_errorCodeDataWriterHolder()
    {
    }

    public logevent_errorCodeDataWriterHolder(Test.logevent_errorCodeDataWriter initialValue)
    {
        value = initialValue;
    }

}
