/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authListDataReaderHolder
{

    public Test.logevent_authListDataReader value = null;

    public logevent_authListDataReaderHolder()
    {
    }

    public logevent_authListDataReaderHolder(Test.logevent_authListDataReader initialValue)
    {
        value = initialValue;
    }

}
