/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:26+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStartTypeSupportHolder
{

    public Test.logevent_appliedSettingsMatchStartTypeSupport value = null;

    public logevent_appliedSettingsMatchStartTypeSupportHolder()
    {
    }

    public logevent_appliedSettingsMatchStartTypeSupportHolder(Test.logevent_appliedSettingsMatchStartTypeSupport initialValue)
    {
        value = initialValue;
    }

}
