/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeat_57130bcbHolder
{

    public Test.logevent_heartbeat_57130bcb value = null;

    public logevent_heartbeat_57130bcbHolder () { }

    public logevent_heartbeat_57130bcbHolder (Test.logevent_heartbeat_57130bcb initialValue)
    {
        value = initialValue;
    }

}
