/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_softwareVersions_1f4be1b2DataReaderHolder
{

    public Test.logevent_softwareVersions_1f4be1b2DataReader value = null;

    public logevent_softwareVersions_1f4be1b2DataReaderHolder()
    {
    }

    public logevent_softwareVersions_1f4be1b2DataReaderHolder(Test.logevent_softwareVersions_1f4be1b2DataReader initialValue)
    {
        value = initialValue;
    }

}
