/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalarsSeqHolder
{

    public Test.logevent_scalars value[] = null;

    public logevent_scalarsSeqHolder()
    {
    }

    public logevent_scalarsSeqHolder(Test.logevent_scalars[] initialValue)
    {
        value = initialValue;
    }

}
