/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface logevent_authList_3447a91eDataReader extends
    Test.logevent_authList_3447a91eDataReaderOperations,
    DDS.DataReader
{
}
