/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public class logevent_simulationMode_fcccc7aeTypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public logevent_simulationMode_fcccc7aeTypeSupport()
    {
        super("Test::logevent_simulationMode_fcccc7ae",
              "",
              "TestID",
              null,
              Test.logevent_simulationMode_fcccc7aeMetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new logevent_simulationMode_fcccc7aeDataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new logevent_simulationMode_fcccc7aeDataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new logevent_simulationMode_fcccc7aeDataReaderViewImpl(this);
    }
}
