/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arraysHolder
{

    public Test.logevent_arrays value = null;

    public logevent_arraysHolder () { }

    public logevent_arraysHolder (Test.logevent_arrays initialValue)
    {
        value = initialValue;
    }

}
