/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevelDataWriterHolder
{

    public Test.logevent_logLevelDataWriter value = null;

    public logevent_logLevelDataWriterHolder()
    {
    }

    public logevent_logLevelDataWriterHolder(Test.logevent_logLevelDataWriter initialValue)
    {
        value = initialValue;
    }

}
