/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsApplied_02b3cc9eDataReaderViewHolder
{

    public Test.logevent_settingsApplied_02b3cc9eDataReaderView value = null;

    public logevent_settingsApplied_02b3cc9eDataReaderViewHolder()
    {
    }

    public logevent_settingsApplied_02b3cc9eDataReaderViewHolder(Test.logevent_settingsApplied_02b3cc9eDataReaderView initialValue)
    {
        value = initialValue;
    }

}
