/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalars_1d41189eDataReaderViewHolder
{

    public Test.logevent_scalars_1d41189eDataReaderView value = null;

    public logevent_scalars_1d41189eDataReaderViewHolder()
    {
    }

    public logevent_scalars_1d41189eDataReaderViewHolder(Test.logevent_scalars_1d41189eDataReaderView initialValue)
    {
        value = initialValue;
    }

}
