/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authListTypeSupportHolder
{

    public Test.logevent_authListTypeSupport value = null;

    public logevent_authListTypeSupportHolder()
    {
    }

    public logevent_authListTypeSupportHolder(Test.logevent_authListTypeSupport initialValue)
    {
        value = initialValue;
    }

}
