/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public class logevent_heartbeat_57130bcbTypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public logevent_heartbeat_57130bcbTypeSupport()
    {
        super("Test::logevent_heartbeat_57130bcb",
              "",
              "TestID",
              null,
              Test.logevent_heartbeat_57130bcbMetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new logevent_heartbeat_57130bcbDataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new logevent_heartbeat_57130bcbDataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new logevent_heartbeat_57130bcbDataReaderViewImpl(this);
    }
}
