/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_softwareVersionsDataReaderViewHolder
{

    public Test.logevent_softwareVersionsDataReaderView value = null;

    public logevent_softwareVersionsDataReaderViewHolder()
    {
    }

    public logevent_softwareVersionsDataReaderViewHolder(Test.logevent_softwareVersionsDataReaderView initialValue)
    {
        value = initialValue;
    }

}
