/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logMessageDataReaderHolder
{

    public Test.logevent_logMessageDataReader value = null;

    public logevent_logMessageDataReaderHolder()
    {
    }

    public logevent_logMessageDataReaderHolder(Test.logevent_logMessageDataReader initialValue)
    {
        value = initialValue;
    }

}
