/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arraysMetaHolder
{

    public static java.lang.String metaDescriptor[] = { "<MetaData version=\"1.0.0\"><Module name=\"Test\"><Struct name=\"logevent_arrays\"><Member name=\"TestID\"><Long/></Member><Member name=\"private_revCode\"><String length=\"8\"/></Member><Member name=\"private_sndStamp\"><Double/></Member><Member name=\"private_rcvStamp\"><Double/></Member><Member name=\"private_seqNum\"><Long/></Member><Member name=\"private_identity\"><String length=\"128\"/></Member><Member name=\"private_origin\"><Long/></Member><Member name=\"private_host\"><Long/></Member><Member name=\"boolean0\"><Array size=\"5\"><Boolean/></Array></Member><Member name=\"byte0\"><Array size=\"5\"><Octet/></Array></Member><Member name=\"short0\"><Array size=\"5\"><Short/></Array></Member><Member name=\"int0\"><Array size=\"5\"><Long/></Array></Member><Member name=\"long0\"><Array size=\"5\"><Long/></Array></Member><Member name=\"longLong0\"><Array size=\"5\"><LongLong/></Array></Member><Member name=\"octet0\"><Array size=\"5\"><Octet/></Array></Member><Member name=\"unsignedShort0\"><Array size=\"5\"><UShort/></Array></Member><Member name=\"unsignedInt0\"><Array size=\"5\"><ULong/></Array></Member><Member name=\"unsignedLong0\"><Array size=\"5\"><ULong/></Array></Member><Member name=\"float0\"><Array size=\"5\"><Float/></Array></Member><Member name=\"double0\"><Array size=\"5\"><Double/></Array></Member><Member name=\"priority\"><Long/></Member></Struct></Module></MetaData>" };

    public logevent_arraysMetaHolder()
    {
    }

}
