/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arraysDataWriterHolder
{

    public Test.logevent_arraysDataWriter value = null;

    public logevent_arraysDataWriterHolder()
    {
    }

    public logevent_arraysDataWriterHolder(Test.logevent_arraysDataWriter initialValue)
    {
        value = initialValue;
    }

}
