/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeat_57130bcbDataWriterHolder
{

    public Test.logevent_heartbeat_57130bcbDataWriter value = null;

    public logevent_heartbeat_57130bcbDataWriterHolder()
    {
    }

    public logevent_heartbeat_57130bcbDataWriterHolder(Test.logevent_heartbeat_57130bcbDataWriter initialValue)
    {
        value = initialValue;
    }

}
