/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_summaryState_7351a054TypeSupportHolder
{

    public Test.logevent_summaryState_7351a054TypeSupport value = null;

    public logevent_summaryState_7351a054TypeSupportHolder()
    {
    }

    public logevent_summaryState_7351a054TypeSupportHolder(Test.logevent_summaryState_7351a054TypeSupport initialValue)
    {
        value = initialValue;
    }

}
