/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStartHolder
{

    public Test.logevent_appliedSettingsMatchStart value = null;

    public logevent_appliedSettingsMatchStartHolder () { }

    public logevent_appliedSettingsMatchStartHolder (Test.logevent_appliedSettingsMatchStart initialValue)
    {
        value = initialValue;
    }

}
