/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStartDataWriterHolder
{

    public Test.logevent_appliedSettingsMatchStartDataWriter value = null;

    public logevent_appliedSettingsMatchStartDataWriterHolder()
    {
    }

    public logevent_appliedSettingsMatchStartDataWriterHolder(Test.logevent_appliedSettingsMatchStartDataWriter initialValue)
    {
        value = initialValue;
    }

}
