/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logMessageMetaHolder
{

    public static java.lang.String metaDescriptor[] = { "<MetaData version=\"1.0.0\"><Module name=\"Test\"><Struct name=\"logevent_logMessage\"><Member name=\"TestID\"><Long/></Member><Member name=\"private_revCode\"><String length=\"8\"/></Member><Member name=\"private_sndStamp\"><Double/></Member><Member name=\"private_rcvStamp\"><Double/></Member><Member name=\"private_seqNum\"><Long/></Member><Member name=\"private_identity\"><String length=\"128\"/></Member><Member name=\"private_origin\"><Long/></Member><Member name=\"private_host\"><Long/></Member><Member name=\"name\"><String/></Member><Member name=\"level\"><Long/></Member><Member name=\"message\"><String/></Member><Member name=\"traceback\"><String/></Member><Member name=\"filePath\"><String/></Member><Member name=\"functionName\"><String/></Member><Member name=\"lineNumber\"><Long/></Member><Member name=\"process\"><Long/></Member><Member name=\"priority\"><Long/></Member></Struct></Module></MetaData>" };

    public logevent_logMessageMetaHolder()
    {
    }

}
