/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_simulationMode_fcccc7aeDataWriterHolder
{

    public Test.logevent_simulationMode_fcccc7aeDataWriter value = null;

    public logevent_simulationMode_fcccc7aeDataWriterHolder()
    {
    }

    public logevent_simulationMode_fcccc7aeDataWriterHolder(Test.logevent_simulationMode_fcccc7aeDataWriter initialValue)
    {
        value = initialValue;
    }

}
