/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalarsTypeSupportHolder
{

    public Test.logevent_scalarsTypeSupport value = null;

    public logevent_scalarsTypeSupportHolder()
    {
    }

    public logevent_scalarsTypeSupportHolder(Test.logevent_scalarsTypeSupport initialValue)
    {
        value = initialValue;
    }

}
