/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authList_3447a91eSeqHolder
{

    public Test.logevent_authList_3447a91e value[] = null;

    public logevent_authList_3447a91eSeqHolder()
    {
    }

    public logevent_authList_3447a91eSeqHolder(Test.logevent_authList_3447a91e[] initialValue)
    {
        value = initialValue;
    }

}
