/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_summaryStateHolder
{

    public Test.logevent_summaryState value = null;

    public logevent_summaryStateHolder () { }

    public logevent_summaryStateHolder (Test.logevent_summaryState initialValue)
    {
        value = initialValue;
    }

}
