/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_errorCode_12906fffSeqHolder
{

    public Test.logevent_errorCode_12906fff value[] = null;

    public logevent_errorCode_12906fffSeqHolder()
    {
    }

    public logevent_errorCode_12906fffSeqHolder(Test.logevent_errorCode_12906fff[] initialValue)
    {
        value = initialValue;
    }

}
