/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public class logevent_softwareVersions_1f4be1b2TypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public logevent_softwareVersions_1f4be1b2TypeSupport()
    {
        super("Test::logevent_softwareVersions_1f4be1b2",
              "",
              "TestID",
              null,
              Test.logevent_softwareVersions_1f4be1b2MetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new logevent_softwareVersions_1f4be1b2DataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new logevent_softwareVersions_1f4be1b2DataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new logevent_softwareVersions_1f4be1b2DataReaderViewImpl(this);
    }
}
