/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arraysDataReaderHolder
{

    public Test.logevent_arraysDataReader value = null;

    public logevent_arraysDataReaderHolder()
    {
    }

    public logevent_arraysDataReaderHolder(Test.logevent_arraysDataReader initialValue)
    {
        value = initialValue;
    }

}
