/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_simulationModeTypeSupportHolder
{

    public Test.logevent_simulationModeTypeSupport value = null;

    public logevent_simulationModeTypeSupportHolder()
    {
    }

    public logevent_simulationModeTypeSupportHolder(Test.logevent_simulationModeTypeSupport initialValue)
    {
        value = initialValue;
    }

}
