/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface logevent_settingVersions_11e4d332DataReaderView extends
    Test.logevent_settingVersions_11e4d332DataReaderViewOperations,
    DDS.DataReaderView
{
}
