/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsApplied_02b3cc9eSeqHolder
{

    public Test.logevent_settingsApplied_02b3cc9e value[] = null;

    public logevent_settingsApplied_02b3cc9eSeqHolder()
    {
    }

    public logevent_settingsApplied_02b3cc9eSeqHolder(Test.logevent_settingsApplied_02b3cc9e[] initialValue)
    {
        value = initialValue;
    }

}
