/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevelTypeSupportHolder
{

    public Test.logevent_logLevelTypeSupport value = null;

    public logevent_logLevelTypeSupportHolder()
    {
    }

    public logevent_logLevelTypeSupportHolder(Test.logevent_logLevelTypeSupport initialValue)
    {
        value = initialValue;
    }

}
