/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logMessage_f4568bfcDataWriterHolder
{

    public Test.logevent_logMessage_f4568bfcDataWriter value = null;

    public logevent_logMessage_f4568bfcDataWriterHolder()
    {
    }

    public logevent_logMessage_f4568bfcDataWriterHolder(Test.logevent_logMessage_f4568bfcDataWriter initialValue)
    {
        value = initialValue;
    }

}
