/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arraysSeqHolder
{

    public Test.logevent_arrays value[] = null;

    public logevent_arraysSeqHolder()
    {
    }

    public logevent_arraysSeqHolder(Test.logevent_arrays[] initialValue)
    {
        value = initialValue;
    }

}
