/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_summaryStateSeqHolder
{

    public Test.logevent_summaryState value[] = null;

    public logevent_summaryStateSeqHolder()
    {
    }

    public logevent_summaryStateSeqHolder(Test.logevent_summaryState[] initialValue)
    {
        value = initialValue;
    }

}
