/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public class logevent_appliedSettingsMatchStart_77f17e02TypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public logevent_appliedSettingsMatchStart_77f17e02TypeSupport()
    {
        super("Test::logevent_appliedSettingsMatchStart_77f17e02",
              "",
              "TestID",
              null,
              Test.logevent_appliedSettingsMatchStart_77f17e02MetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new logevent_appliedSettingsMatchStart_77f17e02DataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new logevent_appliedSettingsMatchStart_77f17e02DataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new logevent_appliedSettingsMatchStart_77f17e02DataReaderViewImpl(this);
    }
}
