/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeatTypeSupportHolder
{

    public Test.logevent_heartbeatTypeSupport value = null;

    public logevent_heartbeatTypeSupportHolder()
    {
    }

    public logevent_heartbeatTypeSupportHolder(Test.logevent_heartbeatTypeSupport initialValue)
    {
        value = initialValue;
    }

}
