/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_summaryState_7351a054Holder
{

    public Test.logevent_summaryState_7351a054 value = null;

    public logevent_summaryState_7351a054Holder () { }

    public logevent_summaryState_7351a054Holder (Test.logevent_summaryState_7351a054 initialValue)
    {
        value = initialValue;
    }

}
