/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevel_7aeafb06DataWriterHolder
{

    public Test.logevent_logLevel_7aeafb06DataWriter value = null;

    public logevent_logLevel_7aeafb06DataWriterHolder()
    {
    }

    public logevent_logLevel_7aeafb06DataWriterHolder(Test.logevent_logLevel_7aeafb06DataWriter initialValue)
    {
        value = initialValue;
    }

}
