/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authList_3447a91eDataReaderHolder
{

    public Test.logevent_authList_3447a91eDataReader value = null;

    public logevent_authList_3447a91eDataReaderHolder()
    {
    }

    public logevent_authList_3447a91eDataReaderHolder(Test.logevent_authList_3447a91eDataReader initialValue)
    {
        value = initialValue;
    }

}
