/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logMessageDataWriterHolder
{

    public Test.logevent_logMessageDataWriter value = null;

    public logevent_logMessageDataWriterHolder()
    {
    }

    public logevent_logMessageDataWriterHolder(Test.logevent_logMessageDataWriter initialValue)
    {
        value = initialValue;
    }

}
