/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface logevent_summaryState_7351a054DataReaderView extends
    Test.logevent_summaryState_7351a054DataReaderViewOperations,
    DDS.DataReaderView
{
}
