/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStartDataReaderViewHolder
{

    public Test.logevent_appliedSettingsMatchStartDataReaderView value = null;

    public logevent_appliedSettingsMatchStartDataReaderViewHolder()
    {
    }

    public logevent_appliedSettingsMatchStartDataReaderViewHolder(Test.logevent_appliedSettingsMatchStartDataReaderView initialValue)
    {
        value = initialValue;
    }

}
