/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_simulationModeDataReaderViewHolder
{

    public Test.logevent_simulationModeDataReaderView value = null;

    public logevent_simulationModeDataReaderViewHolder()
    {
    }

    public logevent_simulationModeDataReaderViewHolder(Test.logevent_simulationModeDataReaderView initialValue)
    {
        value = initialValue;
    }

}
