/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStart_77f17e02DataReaderHolder
{

    public Test.logevent_appliedSettingsMatchStart_77f17e02DataReader value = null;

    public logevent_appliedSettingsMatchStart_77f17e02DataReaderHolder()
    {
    }

    public logevent_appliedSettingsMatchStart_77f17e02DataReaderHolder(Test.logevent_appliedSettingsMatchStart_77f17e02DataReader initialValue)
    {
        value = initialValue;
    }

}
