/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStartDataReaderHolder
{

    public Test.logevent_appliedSettingsMatchStartDataReader value = null;

    public logevent_appliedSettingsMatchStartDataReaderHolder()
    {
    }

    public logevent_appliedSettingsMatchStartDataReaderHolder(Test.logevent_appliedSettingsMatchStartDataReader initialValue)
    {
        value = initialValue;
    }

}
