/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevelSeqHolder
{

    public Test.logevent_logLevel value[] = null;

    public logevent_logLevelSeqHolder()
    {
    }

    public logevent_logLevelSeqHolder(Test.logevent_logLevel[] initialValue)
    {
        value = initialValue;
    }

}
