/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_errorCode_12906fffTypeSupportHolder
{

    public Test.logevent_errorCode_12906fffTypeSupport value = null;

    public logevent_errorCode_12906fffTypeSupportHolder()
    {
    }

    public logevent_errorCode_12906fffTypeSupportHolder(Test.logevent_errorCode_12906fffTypeSupport initialValue)
    {
        value = initialValue;
    }

}
