/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_summaryStateTypeSupportHolder
{

    public Test.logevent_summaryStateTypeSupport value = null;

    public logevent_summaryStateTypeSupportHolder()
    {
    }

    public logevent_summaryStateTypeSupportHolder(Test.logevent_summaryStateTypeSupport initialValue)
    {
        value = initialValue;
    }

}
