/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalars_1d41189eHolder
{

    public Test.logevent_scalars_1d41189e value = null;

    public logevent_scalars_1d41189eHolder () { }

    public logevent_scalars_1d41189eHolder (Test.logevent_scalars_1d41189e initialValue)
    {
        value = initialValue;
    }

}
