/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

import org.opensplice.dds.dcps.Utilities;

public final class logevent_settingsApplied_02b3cc9eDataReaderViewHelper
{

    public static Test.logevent_settingsApplied_02b3cc9eDataReaderView narrow(java.lang.Object obj)
    {
        if (obj == null) {
            return null;
        } else if (obj instanceof Test.logevent_settingsApplied_02b3cc9eDataReaderView) {
            return (Test.logevent_settingsApplied_02b3cc9eDataReaderView)obj;
        } else {
            throw Utilities.createException(Utilities.EXCEPTION_TYPE_BAD_PARAM, null);
        }
    }

    public static Test.logevent_settingsApplied_02b3cc9eDataReaderView unchecked_narrow(java.lang.Object obj)
    {
        if (obj == null) {
            return null;
        } else if (obj instanceof Test.logevent_settingsApplied_02b3cc9eDataReaderView) {
            return (Test.logevent_settingsApplied_02b3cc9eDataReaderView)obj;
        } else {
            throw Utilities.createException(Utilities.EXCEPTION_TYPE_BAD_PARAM, null);
        }
    }

}
