/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface logevent_simulationMode_fcccc7aeDataReaderView extends
    Test.logevent_simulationMode_fcccc7aeDataReaderViewOperations,
    DDS.DataReaderView
{
}
