/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_simulationModeHolder
{

    public Test.logevent_simulationMode value = null;

    public logevent_simulationModeHolder () { }

    public logevent_simulationModeHolder (Test.logevent_simulationMode initialValue)
    {
        value = initialValue;
    }

}
