/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsApplied_02b3cc9eHolder
{

    public Test.logevent_settingsApplied_02b3cc9e value = null;

    public logevent_settingsApplied_02b3cc9eHolder () { }

    public logevent_settingsApplied_02b3cc9eHolder (Test.logevent_settingsApplied_02b3cc9e initialValue)
    {
        value = initialValue;
    }

}
