/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_errorCodeTypeSupportHolder
{

    public Test.logevent_errorCodeTypeSupport value = null;

    public logevent_errorCodeTypeSupportHolder()
    {
    }

    public logevent_errorCodeTypeSupportHolder(Test.logevent_errorCodeTypeSupport initialValue)
    {
        value = initialValue;
    }

}
