/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logMessageHolder
{

    public Test.logevent_logMessage value = null;

    public logevent_logMessageHolder () { }

    public logevent_logMessageHolder (Test.logevent_logMessage initialValue)
    {
        value = initialValue;
    }

}
