/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arrays_5720d768TypeSupportHolder
{

    public Test.logevent_arrays_5720d768TypeSupport value = null;

    public logevent_arrays_5720d768TypeSupportHolder()
    {
    }

    public logevent_arrays_5720d768TypeSupportHolder(Test.logevent_arrays_5720d768TypeSupport initialValue)
    {
        value = initialValue;
    }

}
