/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevelDataReaderViewHolder
{

    public Test.logevent_logLevelDataReaderView value = null;

    public logevent_logLevelDataReaderViewHolder()
    {
    }

    public logevent_logLevelDataReaderViewHolder(Test.logevent_logLevelDataReaderView initialValue)
    {
        value = initialValue;
    }

}
