/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public class logevent_settingsApplied_02b3cc9eTypeSupport extends org.opensplice.dds.dcps.TypeSupportImpl implements DDS.TypeSupportOperations
{
    private static final long serialVersionUID = 1L;

    private long copyCache;

    public logevent_settingsApplied_02b3cc9eTypeSupport()
    {
        super("Test::logevent_settingsApplied_02b3cc9e",
              "",
              "TestID",
              null,
              Test.logevent_settingsApplied_02b3cc9eMetaHolder.metaDescriptor);
    }

    @Override
    protected DDS.DataWriter create_datawriter ()
    {
        return new logevent_settingsApplied_02b3cc9eDataWriterImpl(this);
    }

    @Override
    protected DDS.DataReader create_datareader ()
    {
        return new logevent_settingsApplied_02b3cc9eDataReaderImpl(this);
    }

    @Override
    protected DDS.DataReaderView create_dataview ()
    {
        return new logevent_settingsApplied_02b3cc9eDataReaderViewImpl(this);
    }
}
