/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_simulationModeDataReaderHolder
{

    public Test.logevent_simulationModeDataReader value = null;

    public logevent_simulationModeDataReaderHolder()
    {
    }

    public logevent_simulationModeDataReaderHolder(Test.logevent_simulationModeDataReader initialValue)
    {
        value = initialValue;
    }

}
