/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevelDataReaderHolder
{

    public Test.logevent_logLevelDataReader value = null;

    public logevent_logLevelDataReaderHolder()
    {
    }

    public logevent_logLevelDataReaderHolder(Test.logevent_logLevelDataReader initialValue)
    {
        value = initialValue;
    }

}
