/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingVersions_11e4d332SeqHolder
{

    public Test.logevent_settingVersions_11e4d332 value[] = null;

    public logevent_settingVersions_11e4d332SeqHolder()
    {
    }

    public logevent_settingVersions_11e4d332SeqHolder(Test.logevent_settingVersions_11e4d332[] initialValue)
    {
        value = initialValue;
    }

}
