/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStart_77f17e02DataReaderViewHolder
{

    public Test.logevent_appliedSettingsMatchStart_77f17e02DataReaderView value = null;

    public logevent_appliedSettingsMatchStart_77f17e02DataReaderViewHolder()
    {
    }

    public logevent_appliedSettingsMatchStart_77f17e02DataReaderViewHolder(Test.logevent_appliedSettingsMatchStart_77f17e02DataReaderView initialValue)
    {
        value = initialValue;
    }

}
