/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalarsDataWriterHolder
{

    public Test.logevent_scalarsDataWriter value = null;

    public logevent_scalarsDataWriterHolder()
    {
    }

    public logevent_scalarsDataWriterHolder(Test.logevent_scalarsDataWriter initialValue)
    {
        value = initialValue;
    }

}
