/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_simulationModeDataWriterHolder
{

    public Test.logevent_simulationModeDataWriter value = null;

    public logevent_simulationModeDataWriterHolder()
    {
    }

    public logevent_simulationModeDataWriterHolder(Test.logevent_simulationModeDataWriter initialValue)
    {
        value = initialValue;
    }

}
