/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authListHolder
{

    public Test.logevent_authList value = null;

    public logevent_authListHolder () { }

    public logevent_authListHolder (Test.logevent_authList initialValue)
    {
        value = initialValue;
    }

}
