/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authListSeqHolder
{

    public Test.logevent_authList value[] = null;

    public logevent_authListSeqHolder()
    {
    }

    public logevent_authListSeqHolder(Test.logevent_authList[] initialValue)
    {
        value = initialValue;
    }

}
