/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsAppliedHolder
{

    public Test.logevent_settingsApplied value = null;

    public logevent_settingsAppliedHolder () { }

    public logevent_settingsAppliedHolder (Test.logevent_settingsApplied initialValue)
    {
        value = initialValue;
    }

}
