/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsAppliedDataWriterHolder
{

    public Test.logevent_settingsAppliedDataWriter value = null;

    public logevent_settingsAppliedDataWriterHolder()
    {
    }

    public logevent_settingsAppliedDataWriterHolder(Test.logevent_settingsAppliedDataWriter initialValue)
    {
        value = initialValue;
    }

}
