/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arrays_5720d768DataReaderHolder
{

    public Test.logevent_arrays_5720d768DataReader value = null;

    public logevent_arrays_5720d768DataReaderHolder()
    {
    }

    public logevent_arrays_5720d768DataReaderHolder(Test.logevent_arrays_5720d768DataReader initialValue)
    {
        value = initialValue;
    }

}
