/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authListDataWriterHolder
{

    public Test.logevent_authListDataWriter value = null;

    public logevent_authListDataWriterHolder()
    {
    }

    public logevent_authListDataWriterHolder(Test.logevent_authListDataWriter initialValue)
    {
        value = initialValue;
    }

}
