/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_errorCodeDataReaderViewHolder
{

    public Test.logevent_errorCodeDataReaderView value = null;

    public logevent_errorCodeDataReaderViewHolder()
    {
    }

    public logevent_errorCodeDataReaderViewHolder(Test.logevent_errorCodeDataReaderView initialValue)
    {
        value = initialValue;
    }

}
