/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingVersionsHolder
{

    public Test.logevent_settingVersions value = null;

    public logevent_settingVersionsHolder () { }

    public logevent_settingVersionsHolder (Test.logevent_settingVersions initialValue)
    {
        value = initialValue;
    }

}
