/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_simulationMode_fcccc7aeHolder
{

    public Test.logevent_simulationMode_fcccc7ae value = null;

    public logevent_simulationMode_fcccc7aeHolder () { }

    public logevent_simulationMode_fcccc7aeHolder (Test.logevent_simulationMode_fcccc7ae initialValue)
    {
        value = initialValue;
    }

}
