/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalars_1d41189eSeqHolder
{

    public Test.logevent_scalars_1d41189e value[] = null;

    public logevent_scalars_1d41189eSeqHolder()
    {
    }

    public logevent_scalars_1d41189eSeqHolder(Test.logevent_scalars_1d41189e[] initialValue)
    {
        value = initialValue;
    }

}
