/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_softwareVersionsTypeSupportHolder
{

    public Test.logevent_softwareVersionsTypeSupport value = null;

    public logevent_softwareVersionsTypeSupportHolder()
    {
    }

    public logevent_softwareVersionsTypeSupportHolder(Test.logevent_softwareVersionsTypeSupport initialValue)
    {
        value = initialValue;
    }

}
