/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingVersions_11e4d332DataWriterHolder
{

    public Test.logevent_settingVersions_11e4d332DataWriter value = null;

    public logevent_settingVersions_11e4d332DataWriterHolder()
    {
    }

    public logevent_settingVersions_11e4d332DataWriterHolder(Test.logevent_settingVersions_11e4d332DataWriter initialValue)
    {
        value = initialValue;
    }

}
