/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeatSeqHolder
{

    public Test.logevent_heartbeat value[] = null;

    public logevent_heartbeatSeqHolder()
    {
    }

    public logevent_heartbeatSeqHolder(Test.logevent_heartbeat[] initialValue)
    {
        value = initialValue;
    }

}
