/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeatDataReaderViewHolder
{

    public Test.logevent_heartbeatDataReaderView value = null;

    public logevent_heartbeatDataReaderViewHolder()
    {
    }

    public logevent_heartbeatDataReaderViewHolder(Test.logevent_heartbeatDataReaderView initialValue)
    {
        value = initialValue;
    }

}
