/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsAppliedTypeSupportHolder
{

    public Test.logevent_settingsAppliedTypeSupport value = null;

    public logevent_settingsAppliedTypeSupportHolder()
    {
    }

    public logevent_settingsAppliedTypeSupportHolder(Test.logevent_settingsAppliedTypeSupport initialValue)
    {
        value = initialValue;
    }

}
