/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeatDataReaderHolder
{

    public Test.logevent_heartbeatDataReader value = null;

    public logevent_heartbeatDataReaderHolder()
    {
    }

    public logevent_heartbeatDataReaderHolder(Test.logevent_heartbeatDataReader initialValue)
    {
        value = initialValue;
    }

}
