/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingVersionsDataReaderHolder
{

    public Test.logevent_settingVersionsDataReader value = null;

    public logevent_settingVersionsDataReaderHolder()
    {
    }

    public logevent_settingVersionsDataReaderHolder(Test.logevent_settingVersionsDataReader initialValue)
    {
        value = initialValue;
    }

}
