/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_authListDataReaderViewHolder
{

    public Test.logevent_authListDataReaderView value = null;

    public logevent_authListDataReaderViewHolder()
    {
    }

    public logevent_authListDataReaderViewHolder(Test.logevent_authListDataReaderView initialValue)
    {
        value = initialValue;
    }

}
