/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_summaryStateDataReaderViewHolder
{

    public Test.logevent_summaryStateDataReaderView value = null;

    public logevent_summaryStateDataReaderViewHolder()
    {
    }

    public logevent_summaryStateDataReaderViewHolder(Test.logevent_summaryStateDataReaderView initialValue)
    {
        value = initialValue;
    }

}
