/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeatHolder
{

    public Test.logevent_heartbeat value = null;

    public logevent_heartbeatHolder () { }

    public logevent_heartbeatHolder (Test.logevent_heartbeat initialValue)
    {
        value = initialValue;
    }

}
