/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_softwareVersions_1f4be1b2TypeSupportHolder
{

    public Test.logevent_softwareVersions_1f4be1b2TypeSupport value = null;

    public logevent_softwareVersions_1f4be1b2TypeSupportHolder()
    {
    }

    public logevent_softwareVersions_1f4be1b2TypeSupportHolder(Test.logevent_softwareVersions_1f4be1b2TypeSupport initialValue)
    {
        value = initialValue;
    }

}
