/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public interface logevent_settingsApplied_02b3cc9eDataWriter extends
    Test.logevent_settingsApplied_02b3cc9eDataWriterOperations,
    DDS.DataWriter
{
}
