/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_softwareVersionsHolder
{

    public Test.logevent_softwareVersions value = null;

    public logevent_softwareVersionsHolder () { }

    public logevent_softwareVersionsHolder (Test.logevent_softwareVersions initialValue)
    {
        value = initialValue;
    }

}
