/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_errorCodeSeqHolder
{

    public Test.logevent_errorCode value[] = null;

    public logevent_errorCodeSeqHolder()
    {
    }

    public logevent_errorCodeSeqHolder(Test.logevent_errorCode[] initialValue)
    {
        value = initialValue;
    }

}
