/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arrays_5720d768 {

    public int TestID;
    public java.lang.String private_revCode = "";
    public double private_sndStamp;
    public double private_rcvStamp;
    public int private_seqNum;
    public java.lang.String private_identity = "";
    public int private_origin;
    public int private_host;
    public boolean[] boolean0 = new boolean[5];
    public byte[] byte0 = new byte[5];
    public short[] short0 = new short[5];
    public int[] int0 = new int[5];
    public int[] long0 = new int[5];
    public long[] longLong0 = new long[5];
    public byte[] octet0 = new byte[5];
    public short[] unsignedShort0 = new short[5];
    public int[] unsignedInt0 = new int[5];
    public int[] unsignedLong0 = new int[5];
    public float[] float0 = new float[5];
    public double[] double0 = new double[5];
    public int priority;

    public logevent_arrays_5720d768() {
    }

    public logevent_arrays_5720d768(
        int _TestID,
        java.lang.String _private_revCode,
        double _private_sndStamp,
        double _private_rcvStamp,
        int _private_seqNum,
        java.lang.String _private_identity,
        int _private_origin,
        int _private_host,
        boolean[] _boolean0,
        byte[] _byte0,
        short[] _short0,
        int[] _int0,
        int[] _long0,
        long[] _longLong0,
        byte[] _octet0,
        short[] _unsignedShort0,
        int[] _unsignedInt0,
        int[] _unsignedLong0,
        float[] _float0,
        double[] _double0,
        int _priority)
    {
        TestID = _TestID;
        private_revCode = _private_revCode;
        private_sndStamp = _private_sndStamp;
        private_rcvStamp = _private_rcvStamp;
        private_seqNum = _private_seqNum;
        private_identity = _private_identity;
        private_origin = _private_origin;
        private_host = _private_host;
        boolean0 = _boolean0;
        byte0 = _byte0;
        short0 = _short0;
        int0 = _int0;
        long0 = _long0;
        longLong0 = _longLong0;
        octet0 = _octet0;
        unsignedShort0 = _unsignedShort0;
        unsignedInt0 = _unsignedInt0;
        unsignedLong0 = _unsignedLong0;
        float0 = _float0;
        double0 = _double0;
        priority = _priority;
    }

}
