/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_heartbeatDataWriterHolder
{

    public Test.logevent_heartbeatDataWriter value = null;

    public logevent_heartbeatDataWriterHolder()
    {
    }

    public logevent_heartbeatDataWriterHolder(Test.logevent_heartbeatDataWriter initialValue)
    {
        value = initialValue;
    }

}
