/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_appliedSettingsMatchStart_77f17e02SeqHolder
{

    public Test.logevent_appliedSettingsMatchStart_77f17e02 value[] = null;

    public logevent_appliedSettingsMatchStart_77f17e02SeqHolder()
    {
    }

    public logevent_appliedSettingsMatchStart_77f17e02SeqHolder(Test.logevent_appliedSettingsMatchStart_77f17e02[] initialValue)
    {
        value = initialValue;
    }

}
