/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalars_1d41189eDataWriterHolder
{

    public Test.logevent_scalars_1d41189eDataWriter value = null;

    public logevent_scalars_1d41189eDataWriterHolder()
    {
    }

    public logevent_scalars_1d41189eDataWriterHolder(Test.logevent_scalars_1d41189eDataWriter initialValue)
    {
        value = initialValue;
    }

}
