/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsAppliedDataReaderHolder
{

    public Test.logevent_settingsAppliedDataReader value = null;

    public logevent_settingsAppliedDataReaderHolder()
    {
    }

    public logevent_settingsAppliedDataReaderHolder(Test.logevent_settingsAppliedDataReader initialValue)
    {
        value = initialValue;
    }

}
