/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:31+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arrays_5720d768SeqHolder
{

    public Test.logevent_arrays_5720d768 value[] = null;

    public logevent_arrays_5720d768SeqHolder()
    {
    }

    public logevent_arrays_5720d768SeqHolder(Test.logevent_arrays_5720d768[] initialValue)
    {
        value = initialValue;
    }

}
