/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingVersions_11e4d332DataReaderViewHolder
{

    public Test.logevent_settingVersions_11e4d332DataReaderView value = null;

    public logevent_settingVersions_11e4d332DataReaderViewHolder()
    {
    }

    public logevent_settingVersions_11e4d332DataReaderViewHolder(Test.logevent_settingVersions_11e4d332DataReaderView initialValue)
    {
        value = initialValue;
    }

}
