/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:27+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_arraysTypeSupportHolder
{

    public Test.logevent_arraysTypeSupport value = null;

    public logevent_arraysTypeSupportHolder()
    {
    }

    public logevent_arraysTypeSupportHolder(Test.logevent_arraysTypeSupport initialValue)
    {
        value = initialValue;
    }

}
