/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingsApplied_02b3cc9eTypeSupportHolder
{

    public Test.logevent_settingsApplied_02b3cc9eTypeSupport value = null;

    public logevent_settingsApplied_02b3cc9eTypeSupportHolder()
    {
    }

    public logevent_settingsApplied_02b3cc9eTypeSupportHolder(Test.logevent_settingsApplied_02b3cc9eTypeSupport initialValue)
    {
        value = initialValue;
    }

}
