/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:32+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_logLevel_7aeafb06SeqHolder
{

    public Test.logevent_logLevel_7aeafb06 value[] = null;

    public logevent_logLevel_7aeafb06SeqHolder()
    {
    }

    public logevent_logLevel_7aeafb06SeqHolder(Test.logevent_logLevel_7aeafb06[] initialValue)
    {
        value = initialValue;
    }

}
