/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_settingVersionsTypeSupportHolder
{

    public Test.logevent_settingVersionsTypeSupport value = null;

    public logevent_settingVersionsTypeSupportHolder()
    {
    }

    public logevent_settingVersionsTypeSupportHolder(Test.logevent_settingVersionsTypeSupport initialValue)
    {
        value = initialValue;
    }

}
