/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:24+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class logevent_scalarsMetaHolder
{

    public static java.lang.String metaDescriptor[] = { "<MetaData version=\"1.0.0\"><Module name=\"Test\"><Struct name=\"logevent_scalars\"><Member name=\"TestID\"><Long/></Member><Member name=\"private_revCode\"><String length=\"8\"/></Member><Member name=\"private_sndStamp\"><Double/></Member><Member name=\"private_rcvStamp\"><Double/></Member><Member name=\"private_seqNum\"><Long/></Member><Member name=\"private_identity\"><String length=\"128\"/></Member><Member name=\"private_origin\"><Long/></Member><Member name=\"private_host\"><Long/></Member><Member name=\"boolean0\"><Boolean/></Member><Member name=\"byte0\"><Octet/></Member><Member name=\"char0\"><String/></Member><Member name=\"short0\"><Short/></Member><Member name=\"int0\"><Long/></Member><Member name=\"long0\"><Long/></Member><Member name=\"longLong0\"><LongLong/></Member><Member name=\"octet0\"><Octet/></Member><Member name=\"unsignedShort0\"><UShort/></Member><Member name=\"unsignedInt0\"><ULong/></Member><Member name=\"unsignedLong0\"><ULong/></Member><Member name=\"float0\"><Float/></Member><Member name=\"double0\"><Double/></Member><Member name=\"string0\"><String length=\"20\"/></Member><Member name=\"priority\"><Long/></Member></Struct></Module></MetaData>" };

    public logevent_scalarsMetaHolder()
    {
    }

}
