/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:33+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class scalars_e4001923DataReaderViewHolder
{

    public Test.scalars_e4001923DataReaderView value = null;

    public scalars_e4001923DataReaderViewHolder()
    {
    }

    public scalars_e4001923DataReaderViewHolder(Test.scalars_e4001923DataReaderView initialValue)
    {
        value = initialValue;
    }

}
