/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class scalars_e4001923Holder
{

    public Test.scalars_e4001923 value = null;

    public scalars_e4001923Holder () { }

    public scalars_e4001923Holder (Test.scalars_e4001923 initialValue)
    {
        value = initialValue;
    }

}
