/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class scalarsDataWriterHolder
{

    public Test.scalarsDataWriter value = null;

    public scalarsDataWriterHolder()
    {
    }

    public scalarsDataWriterHolder(Test.scalarsDataWriter initialValue)
    {
        value = initialValue;
    }

}
