/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:28+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class scalarsTypeSupportHolder
{

    public Test.scalarsTypeSupport value = null;

    public scalarsTypeSupportHolder()
    {
    }

    public scalarsTypeSupportHolder(Test.scalarsTypeSupport initialValue)
    {
        value = initialValue;
    }

}
