/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:29+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class scalarsDataReaderHolder
{

    public Test.scalarsDataReader value = null;

    public scalarsDataReaderHolder()
    {
    }

    public scalarsDataReaderHolder(Test.scalarsDataReader initialValue)
    {
        value = initialValue;
    }

}
