/**
 * This file is auto-generated by idlpp
 * 
 * Source: sal_Test.idl
 * Generated on: 2021-04-15T19:02:34+0000
 * OpenSplice 6.11.0
 */
package Test;

public final class scalarsHolder
{

    public Test.scalars value = null;

    public scalarsHolder () { }

    public scalarsHolder (Test.scalars initialValue)
    {
        value = initialValue;
    }

}
